-- MySQL Script generated by MySQL Workbench
-- Sun 05 Aug 2018 07:54:40 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES'; */

-- -----------------------------------------------------
-- Schema heimdali
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `heimdali`.`ldap_registration`
-- -----------------------------------------------------

CREATE TABLE ldap_registration (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  distinguished_name VARCHAR2(255) NOT NULL,
  common_name VARCHAR2(255) NOT NULL,
  existing CHAR(1) DEFAULT 0 NOT NULL,
  sentry_role VARCHAR2(255) NOT NULL,
  group_created TIMESTAMP(0) NULL,
  role_created TIMESTAMP(0) NULL,
  group_associated TIMESTAMP(0) NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `heimdali`.`hive_grant`
-- -----------------------------------------------------

CREATE TABLE hive_grant (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  ldap_registration_id NUMBER NOT NULL,
  location_access TIMESTAMP(0) NULL,
  database_access TIMESTAMP(0) NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_hive_grant_ldap_r1
    FOREIGN KEY (ldap_registration_id)
    REFERENCES ldap_registration (id)
   )
;

CREATE INDEX fk_hive_grant_ldap_r_idx ON hive_grant (ldap_registration_id);


-- -----------------------------------------------------
-- Table `heimdali`.`hive_database`
-- -----------------------------------------------------

CREATE TABLE hive_database (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  name VARCHAR2(255) NOT NULL,
  location VARCHAR2(255) NOT NULL,
  size_in_gb NUMBER(10) NOT NULL,
  directory_created TIMESTAMP(0) NULL,
  quota_set TIMESTAMP(0) NULL,
  database_created TIMESTAMP(0) NULL,
  manager_group_id NUMBER NOT NULL,
  readonly_group_id NUMBER NULL,
  readwrite_group_id NUMBER NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_hive_database_hive_grant1
    FOREIGN KEY (manager_group_id)
    REFERENCES hive_grant (id)
   ,
  CONSTRAINT fk_hive_database_hive_grant2
    FOREIGN KEY (readonly_group_id)
    REFERENCES hive_grant (id)
   ,
  CONSTRAINT fk_hive_database_hive_grant3
   FOREIGN KEY (readwrite_group_id)
   REFERENCES hive_grant (id)
   );

CREATE INDEX fk_hive_database_grant1_idx ON hive_database (manager_group_id);
CREATE INDEX fk_hive_database_grant2_idx ON hive_database (readonly_group_id);
CREATE INDEX fk_hive_database_grant3_idx ON hive_database (readwrite_group_id);


-- -----------------------------------------------------
-- Table `heimdali`.`resource_pool`
-- -----------------------------------------------------

CREATE TABLE resource_pool (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  pool_name VARCHAR2(255) NOT NULL,
  max_cores NUMBER(10) NOT NULL,
  max_memory_in_gb NUMBER(10) NOT NULL,
  created TIMESTAMP(0) NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `heimdali`.`compliance`
-- -----------------------------------------------------
CREATE TABLE compliance (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  phi_data CHAR(1) NOT NULL,
  pii_data CHAR(1) NOT NULL,
  pci_data CHAR(1) NOT NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `heimdali`.`workspace_request`
-- -----------------------------------------------------
CREATE TABLE workspace_request (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  name VARCHAR2(255) NOT NULL,
  compliance_id NUMBER NOT NULL,
  requested_by VARCHAR2(255) NOT NULL,
  request_date TIMESTAMP(0) NOT NULL,
  single_user CHAR(1) DEFAULT 0 NOT NULL,
  summary varchar(255) NOT NULL,
  description varchar2(4000) NOT NULL,
  behavior varchar(50) NOT NULL,
  workspace_created TIMESTAMP NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_workspace_request_cmplnc1
    FOREIGN KEY (compliance_id)
    REFERENCES compliance (id)
   )
;

CREATE INDEX fk_wk_request_cmplnc1_idx ON workspace_request (compliance_id);


-- -----------------------------------------------------
-- Table `heimdali`.`approval`
-- -----------------------------------------------------
CREATE TABLE approval (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  role varchar2(25) NOT NULL,
  approver VARCHAR2(255) NOT NULL,
  approval_time TIMESTAMP(0) NOT NULL,
  workspace_request_id NUMBER NOT NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_approval_wks_request1
    FOREIGN KEY (workspace_request_id)
    REFERENCES workspace_request (id)
   )
;

CREATE INDEX fk_approval_wks_request1_idx ON approval (workspace_request_id);


-- -----------------------------------------------------
-- Table `heimdali`.`member`
-- -----------------------------------------------------
CREATE TABLE member (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  distinguished_name VARCHAR2(255) NOT NULL,
  ldap_registration_id NUMBER NOT NULL,
  created TIMESTAMP(0) NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_member_ldap_reg1
    FOREIGN KEY (ldap_registration_id)
    REFERENCES ldap_registration (id)
   )
;

CREATE INDEX fk_member_ldap_reg1_idx ON member (ldap_registration_id);


-- -----------------------------------------------------
-- Table `heimdali`.`provision_task`
-- -----------------------------------------------------
CREATE TABLE provision_task (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  name VARCHAR2(255) NOT NULL,
  completed TIMESTAMP(0) NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table `heimdali`.`task_log`
-- -----------------------------------------------------

CREATE TABLE task_log (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  message VARCHAR2(255) NOT NULL,
  provision_task_id NUMBER NOT NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_table1_provision_task1
    FOREIGN KEY (provision_task_id)
    REFERENCES provision_task (id)
   )
;

CREATE INDEX fk_table1_provision_task1_idx ON task_log (provision_task_id);


-- -----------------------------------------------------
-- Table `heimdali`.`topic_grant`
-- -----------------------------------------------------
CREATE TABLE topic_grant (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  ldap_registration_id NUMBER NOT NULL,
  topic_access TIMESTAMP(0) NULL,
  actions VARCHAR2(255) NOT NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_topic_role_ldap_reg1
    FOREIGN KEY (ldap_registration_id)
    REFERENCES ldap_registration (id)
   )
;

CREATE INDEX fk_topic_role_ldap_reg1_idx ON topic_grant (ldap_registration_id);


-- -----------------------------------------------------
-- Table `heimdali`.`kafka_topic`
-- -----------------------------------------------------
CREATE TABLE kafka_topic (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  name VARCHAR2(255) NOT NULL,
  partitions NUMBER(10) NOT NULL,
  replication_factor NUMBER(10) NOT NULL,
  manager_role_id NUMBER NOT NULL,
  readonly_role_id NUMBER NOT NULL,
  topic_created TIMESTAMP(0) NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_kafka_topic_topic_role1
    FOREIGN KEY (manager_role_id)
    REFERENCES topic_grant (id)
   ,
  CONSTRAINT fk_kafka_topic_topic_role2
    FOREIGN KEY (readonly_role_id)
    REFERENCES topic_grant (id)
   )
;

CREATE INDEX fk_kafka_topic_topic_role1_idx ON kafka_topic (manager_role_id);
CREATE INDEX fk_kafka_topic_topic_role2_idx ON kafka_topic (readonly_role_id);


-- -----------------------------------------------------
-- Table `heimdali`.`application`
-- -----------------------------------------------------
CREATE TABLE application (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  name VARCHAR2(45) NOT NULL,
  consumer_group_name VARCHAR2(255) NOT NULL,
  ldap_registration_id NUMBER NOT NULL,
  application_type VARCHAR(255) NULL,
  logo VARCHAR(255) NULL,
  language VARCHAR(255) NULL,
  repository VARCHAR(255) NULL,
  consumer_group_access TIMESTAMP(0) NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_application_ldap_reg1
    FOREIGN KEY (ldap_registration_id)
    REFERENCES ldap_registration (id)
   )
;

CREATE INDEX fk_application_ldap_reg1_idx ON application (ldap_registration_id);


-- -----------------------------------------------------
-- Table `heimdali`.`workspace_topic`
-- -----------------------------------------------------
CREATE TABLE workspace_topic (
  workspace_request_id NUMBER NOT NULL,
  kafka_topic_id NUMBER NOT NULL,
  workspace_created TIMESTAMP NULL,
  PRIMARY KEY (workspace_request_id, kafka_topic_id)
 ,
  CONSTRAINT fk_ws_rq_has_topic_ws_rq1
    FOREIGN KEY (workspace_request_id)
    REFERENCES workspace_request (id)
   ,
  CONSTRAINT fk_ws_rq_has_topic_topic1
    FOREIGN KEY (kafka_topic_id)
    REFERENCES kafka_topic (id)
   )
;

CREATE INDEX fk_ws_topic_idx1 ON workspace_topic (kafka_topic_id);
CREATE INDEX fk_ws_topic_idx2 ON workspace_topic (workspace_request_id);


-- -----------------------------------------------------
-- Table `heimdali`.`workspace_database`
-- -----------------------------------------------------
CREATE TABLE workspace_database (
  workspace_request_id NUMBER NOT NULL,
  hive_database_id NUMBER NOT NULL,
  PRIMARY KEY (workspace_request_id, hive_database_id)
 ,
  CONSTRAINT fk_ws_db_cnstrnt1
    FOREIGN KEY (workspace_request_id)
    REFERENCES workspace_request (id)
   ,
  CONSTRAINT fk_ws_db_cnstrnt2
    FOREIGN KEY (hive_database_id)
    REFERENCES hive_database (id)
   )
;

CREATE INDEX fk_ws_db_idx1 ON workspace_database (hive_database_id);
CREATE INDEX fk_ws_db_idx2 ON workspace_database (workspace_request_id);


-- -----------------------------------------------------
-- Table `heimdali`.`workspace_pool`
-- -----------------------------------------------------
CREATE TABLE workspace_pool (
  workspace_request_id NUMBER NOT NULL,
  resource_pool_id NUMBER NOT NULL,
  PRIMARY KEY (workspace_request_id, resource_pool_id)
 ,
  CONSTRAINT fk_ws_pool_cnstrnt1
    FOREIGN KEY (workspace_request_id)
    REFERENCES workspace_request (id)
   ,
  CONSTRAINT fk_ws_pool_cnstrnt2
    FOREIGN KEY (resource_pool_id)
    REFERENCES resource_pool (id)
   )
;

CREATE INDEX fk_wks_rq_idx1 ON workspace_pool (resource_pool_id);
CREATE INDEX fk_wks_rq_idx2 ON workspace_pool (workspace_request_id);


-- -----------------------------------------------------
-- Table `heimdali`.`workspace_application`
-- -----------------------------------------------------
CREATE TABLE workspace_application (
  application_id NUMBER NOT NULL,
  workspace_request_id NUMBER NOT NULL,
  PRIMARY KEY (application_id, workspace_request_id)
 ,
  CONSTRAINT fk_application__cnstrnt1
    FOREIGN KEY (application_id)
    REFERENCES application (id)
   ,
  CONSTRAINT fk_application_cnstrnt2
    FOREIGN KEY (workspace_request_id)
    REFERENCES workspace_request (id)
   )
;

CREATE INDEX fk_app_idx1 ON workspace_application (workspace_request_id);
CREATE INDEX fk_app_idx2 ON workspace_application (application_id);

-- -----------------------------------------------------
-- Table `heimdali`.`heimdali_config`
-- -----------------------------------------------------
CREATE TABLE heimdali_config (
  config_key VARCHAR2(255) NOT NULL,
  config_value VARCHAR2(255) NOT NULL,
  PRIMARY KEY (config_key));


-- -----------------------------------------------------
-- Table `heimdali`.`ldap_attribute`
-- -----------------------------------------------------

CREATE TABLE ldap_attribute (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  attr_key VARCHAR(255) NOT NULL,
  attr_value VARCHAR(255) NOT NULL,
  ldap_registration_id NUMBER NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_ldap_attribute_cnstrnt1
    FOREIGN KEY (ldap_registration_id)
    REFERENCES ldap_registration (id) NOT DEFERRABLE);

CREATE INDEX fk_ldap_attribute_idx1 ON ldap_attribute(ldap_registration_id);


INSERT INTO heimdali_config (config_key, config_value)
    SELECT 'nextgid', coalesce(max(cast(attr_key as NUMBER)), 1039493) + 1 from ldap_attribute where attr_key = 'nextgid';

INSERT INTO ldap_attribute (ldap_registration_id, attr_key, attr_value)
SELECT id, 'dn', distinguished_name FROM ldap_registration;

INSERT INTO ldap_attribute (ldap_registration_id, attr_key, attr_value)
SELECT id, 'objectClass', 'group' FROM ldap_registration;

INSERT INTO ldap_attribute (ldap_registration_id, attr_key, attr_value)
SELECT id, 'objectClass', 'top' FROM ldap_registration;

INSERT INTO ldap_attribute (ldap_registration_id, attr_key, attr_value)
SELECT id, 'sAMAccountName', common_name FROM ldap_registration;

INSERT INTO ldap_attribute (ldap_registration_id, attr_key, attr_value)
SELECT id, 'cn', common_name FROM ldap_registration;

INSERT INTO ldap_attribute (ldap_registration_id, attr_key, attr_value)
SELECT id, 'msSFU30Name', common_name FROM ldap_registration;

INSERT INTO ldap_attribute (ldap_registration_id, attr_key, attr_value)
SELECT id, 'msSFU30NisDomain', 'jotunn' FROM ldap_registration; 

INSERT INTO ldap_attribute (ldap_registration_id, attr_key, attr_value)
SELECT id, 'gidNumber', ROW_NUMBER() OVER (ORDER BY id) + 1039493 FROM ldap_registration;


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
